# Generated by Django 4.2 on 2023-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("farmer", "FARMER"),
                    ("store_keeper", "STORE KEEPER"),
                    ("support", "SUPPORT"),
                ],
                default=("farmer", "FARMER"),
                help_text="Your Profession ...!",
                max_length=60,
                verbose_name="Choice",
            ),
        ),
    ]
