# Generated by Django 4.2 on 2023-07-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="store_type",
            field=models.CharField(
                choices=[
                    ("farm", "FARM PRODUCTS"),
                    ("agric", "AGRIC PRODUCTS"),
                    ("service", "SERVICES"),
                ],
                default=("farm", "FARM PRODUCTS"),
                max_length=50,
                verbose_name="Store type",
            ),
        ),
    ]
